### ISSUE TITLE
style.css de cuadro con botones 1ra pag

### ISSUE THREAD

**Issue by NatalyVerdugoNogue** [NatalyVerdugoNogue/scl-2018-05-bc-core-am-datadashboard#3]
modificar estilo
`<div id="pais1">
     <p id="txt1">${country.name}</p>
     <button id="btnUno">CONTINUAR</button>
     </div>`

en div y p hacerlo con class, así modificamos estilos generales
responsive para que botones siempre esten contenidos en el div

**Comment by BetsabeMP** [comment]
ya está listo

**Comment by NatalyVerdugoNogue** [comment]
revisado y listo
